version: "3.8"

services:
  postgres:
    # image: postgres:15
    image: pgvector/pgvector:pg15
    container_name: demo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ex1234
      POSTGRES_DB: test-db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgresql-logs:/log/postgresql
    # 기본 설정 파일과 내가 지정한 conf 파일 변경 시 에러 문제 발생(커맨드로 설정 추가하도록 수정)  
    command: |
      postgres 
      -c logging_collector=on
      -c log_directory=/log/postgresql
      -c log_filename=postgresql.log
      -c log_line_prefix='%m [%p] '
      -c log_statement=all
      -c log_min_messages=warning
      -c log_min_error_statement=error
      -c log_timezone=UTC

    networks:
      - default

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.13.4
    container_name: postgres-filebeat
    ports:
      - 15044:15044
    user: root
    volumes:
      - ./postgresql-logs:/var/log/postgresql
    # entrypoint: ["/bin/sh", "/usr/local/bin/entrypoint.sh"]
    depends_on:
      - postgres
    networks:
      - default
      - test-env_default # Kafka 컨테이너가 있는 네트워크에 연결

volumes:
  pgdata:

networks:
  default:
  test-env_default:
    external: true # 기존 Kafka 네트워크를 외부에서 참조
